"use client";
import {useState} from "react";
type Rule={id:string;key:string;title:string;enabled:boolean;priority:number;conditions:Record<string,unknown>;action:Record<string,unknown>};
type Weights={strength:number;endurance:number;athleticism:number;mobility:number;recovery:number;fuel:number;consistency:number};
type Engine={formula:{sleepTargetHours:number;proteinTargetGPerKg:number;waterTargetMl:number;checkinsPerWeek:number;performanceChangeMultiplier:number};radar:{green:number;amber:number}};
export default function RulesClient({rules:initial,weights:initialWeights,engine:initialEngine}:{rules:Rule[];weights:Weights;engine:Engine}){
 const [rules,setRules]=useState(initial);const [weights,setWeights]=useState(initialWeights);const [engine,setEngine]=useState(initialEngine);const [status,setStatus]=useState("");
 async function patchRule(i:number,patch:Partial<Rule>){const next=[...rules];next[i]={...next[i],...patch};setRules(next);const body:any={};for(const k of ["enabled","priority","conditions","action"] as const)if(k in patch)body[k]=patch[k];const r=await fetch(`/api/admin/rules/${next[i].id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(body)});setStatus(r.ok?"Regel gespeichert.":"Regel konnte nicht gespeichert werden.");}
 async function saveRuleJson(i:number,field:"conditions"|"action",value:string){try{await patchRule(i,{[field]:JSON.parse(value)} as any)}catch{setStatus("JSON ist ungültig.");}}
 async function saveWeights(){const r=await fetch("/api/admin/score-settings",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(weights)});setStatus(r.ok?"Gewichte gespeichert.":"Summe muss genau 100 ergeben.");}
 async function saveEngine(){const r=await fetch("/api/admin/engine-settings",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(engine)});setStatus(r.ok?"Score Formel und Radar gespeichert.":"Engine Einstellungen sind ungültig.");}
 return <div className="rules-admin-stack">
  <article className="panel"><span className="eyebrow">TRAINERING ENGINE</span><h2>Transparente Regeln</h2><p className="muted">Alle aktiven Regeln werden serverseitig ausgewertet. Der Trainer entscheidet abschließend über Planänderungen.</p><div className="rule-editor-list">{rules.map((r,i)=><details className="rule-editor" key={r.id}><summary><button type="button" className={r.enabled?"toggle on":"toggle"} onClick={e=>{e.preventDefault();patchRule(i,{enabled:!r.enabled})}}>{r.enabled?"ON":"OFF"}</button><div><strong>{r.title}</strong><small>{r.key}</small></div><span>Priority {r.priority}</span></summary><div className="rule-editor-body"><label>Priorität<input type="number" min="0" max="1000" defaultValue={r.priority} onBlur={e=>patchRule(i,{priority:Number(e.target.value)})}/></label><label>Bedingungen JSON<textarea defaultValue={JSON.stringify(r.conditions,null,2)} onBlur={e=>saveRuleJson(i,"conditions",e.target.value)}/></label><label>Aktion JSON<textarea defaultValue={JSON.stringify(r.action,null,2)} onBlur={e=>saveRuleJson(i,"action",e.target.value)}/></label></div></details>)}</div></article>
  <div className="admin-cols"><article className="panel"><span className="eyebrow">GEWICHTUNG LEISTUNGSWERT</span><h2>100 Prozent</h2><div className="weights">{Object.entries(weights).map(([key,val])=><label className="weight" key={key}><span>{key.toUpperCase()}</span><input type="number" min="0" max="100" value={val} onChange={e=>setWeights({...weights,[key]:Number(e.target.value)})}/><strong>{val}%</strong></label>)}</div><button className="secondary full" onClick={saveWeights}>GEWICHTE SPEICHERN</button></article>
  <article className="panel mini-form"><span className="eyebrow">FORMEL & RADAR</span><h2>Ziele und Schwellen</h2><label>Schlaf Ziel Stunden<input type="number" step=".1" value={engine.formula.sleepTargetHours} onChange={e=>setEngine({...engine,formula:{...engine.formula,sleepTargetHours:Number(e.target.value)}})}/></label><label>Protein g pro kg<input type="number" step=".1" value={engine.formula.proteinTargetGPerKg} onChange={e=>setEngine({...engine,formula:{...engine.formula,proteinTargetGPerKg:Number(e.target.value)}})}/></label><label>Wasser Ziel ml<input type="number" value={engine.formula.waterTargetMl} onChange={e=>setEngine({...engine,formula:{...engine.formula,waterTargetMl:Number(e.target.value)}})}/></label><label>Check ins pro Woche<input type="number" value={engine.formula.checkinsPerWeek} onChange={e=>setEngine({...engine,formula:{...engine.formula,checkinsPerWeek:Number(e.target.value)}})}/></label><label>Leistungsmultiplikator<input type="number" value={engine.formula.performanceChangeMultiplier} onChange={e=>setEngine({...engine,formula:{...engine.formula,performanceChangeMultiplier:Number(e.target.value)}})}/></label><label>Radar Grün ab<input type="number" value={engine.radar.green} onChange={e=>setEngine({...engine,radar:{...engine.radar,green:Number(e.target.value)}})}/></label><label>Radar Gelb ab<input type="number" value={engine.radar.amber} onChange={e=>setEngine({...engine,radar:{...engine.radar,amber:Number(e.target.value)}})}/></label><button className="secondary full" onClick={saveEngine}>ENGINE SPEICHERN</button></article></div>{status&&<div className="save-toast">{status}</div>}
 </div>;
}