"use client";
import {Copy,LocalizedElement} from "../components/Locale";

import {FormEvent,useState} from "react";
type Product={name:string;brand:string;officialNutriScore:string|null;per100g:{calories:number|null;proteinG:number|null;carbsG:number|null;fatG:number|null;sugarG:number|null}};
export default function FuelClient(){
 const [status,setStatus]=useState("");const [product,setProduct]=useState<Product|null>(null);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const body={calories:Number(f.get("calories"))||undefined,proteinG:Number(f.get("proteinG"))||undefined,carbsG:Number(f.get("carbsG"))||undefined,fatG:Number(f.get("fatG"))||undefined,waterMl:Number(f.get("waterMl"))||undefined,fruitVegServings:Number(f.get("fruitVegServings"))||undefined,addedSugarG:Number(f.get("addedSugarG"))||undefined,processedFoodScore:Number(f.get("processedFoodScore"))||undefined,source:"manual"};const r=await fetch("/api/nutrition",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const j=await r.json().catch(()=>({}));setStatus(r.ok?"Ernährung gespeichert.":j.error||"Speichern fehlgeschlagen.");if(r.ok)setTimeout(()=>location.reload(),500)}
 async function lookup(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const code=String(f.get("barcode")||"").trim();setStatus("Suche…");const r=await fetch(`/api/food/barcode/${encodeURIComponent(code)}`);const j=await r.json().catch(()=>({}));if(r.ok){setProduct(j.product);setStatus("")}else setStatus(j.error||"Nicht gefunden.")}
 return <div className="fuel-actions">
   <form className="panel mini-form" onSubmit={save}><span className="eyebrow"><Copy text={"HEUTIGE ERNÄHRUNG"}/></span><h2><Copy text={"Tag eintragen"}/></h2><div className="input-grid"><input name="calories" type="number" placeholder="Kalorien"/><input name="proteinG" type="number" step=".1" placeholder="Protein g"/><LocalizedElement as="input" name="carbsG" type="number" step=".1" placeholder="Kohlenhydrate g"/><LocalizedElement as="input" name="fatG" type="number" step=".1" placeholder="Fett g"/><LocalizedElement as="input" name="waterMl" type="number" placeholder="Wasser ml"/><LocalizedElement as="input" name="fruitVegServings" type="number" step=".5" placeholder="Obst Gemüse Portionen"/><LocalizedElement as="input" name="addedSugarG" type="number" step=".1" placeholder="Zucker g"/><LocalizedElement as="input" name="processedFoodScore" type="number" min="0" max="100" placeholder="Verarbeitet 0 bis 100"/></div><button className="primary compact"><Copy text={"ERNÄHRUNG SPEICHERN →"}/></button></form>
   <form className="panel mini-form" onSubmit={lookup}><span className="eyebrow">BARCODE</span><h2><Copy text={"Lebensmittel prüfen"}/></h2><LocalizedElement as="input" name="barcode" inputMode="numeric" pattern="[0-9]{8,14}" placeholder="Barcode eingeben" required/><button className="secondary"><Copy text={"LEBENSMITTEL SUCHEN"}/></button>{product&&<div className="food-result"><strong>{product.name}</strong><span>{product.brand}</span><div><b>{product.per100g.calories??"—"} kcal</b><b>{product.per100g.proteinG??"—"}<Copy text={"g Protein"}/></b><b><Copy text={"NUTRI WERT"}/>{product.officialNutriScore??"—"}</b></div></div>}</form>
   {status&&<div className="save-toast"><Copy text={status}/></div>}
 </div>;
}