
import {Copy} from "../components/Locale";
import Link from "next/link";import {requireUser} from "../../lib/auth";import {prisma} from "../../lib/db";import {hasFeature} from "../../lib/entitlements";import FuelClient from "./FuelClient";export const dynamic="force-dynamic";
function grade(score:number|null|undefined){if(score==null)return"Keine Angabe";if(score>=80)return"A";if(score>=65)return"B";if(score>=50)return"C";if(score>=35)return"D";return"E"}
export default async function Fuel(){const user=await requireUser();const allowed=await hasFeature(user.subscriptionTier,"nutrition_fuel");if(!allowed)return <main className="sub-shell"><section className="locked-feature panel"><span className="eyebrow"><Copy text={"ERNÄHRUNG · PRO"}/></span><h1><Copy text={"Ernährung wird Teil deines Systems."}/></h1><p><Copy text={"Kalorien, Makros, Wasser, Qualität und Barcode gehören zu PRO."}/></p><Link className="primary compact" href="/pricing"><Copy text={"PRO TESTEN"}/></Link></section></main>;
 const [items,wearable,body]=await Promise.all([prisma.nutritionDaily.findMany({where:{userId:user.id},orderBy:{date:"desc"},take:30}),prisma.wearableDaily.findFirst({where:{userId:user.id},orderBy:{date:"desc"}}),prisma.bodyMetric.findFirst({where:{userId:user.id},orderBy:{date:"desc"}})]);
 const today=items[0];let expenditure=wearable?.totalCalories??null;
 if(expenditure==null&&wearable?.activeCalories!=null&&user.birthDate&&user.heightCm&&body?.weightKg){const age=Math.floor((Date.now()-user.birthDate.getTime())/31557600000);const sex=user.sex==="male"?5:user.sex==="female"?-161:-78;const bmr=10*body.weightKg+6.25*user.heightCm-5*age+sex;expenditure=Math.round(bmr+wearable.activeCalories)}
 const balance=today?.calories!=null&&expenditure!=null?Math.round(today.calories-expenditure):null;
 return <main className="sub-shell"><header className="sub-top"><Link href="/dashboard" className="brand">BE <span>DIFFERENT</span></Link></header><section className="page-hero compact-hero"><div><span className="eyebrow"><Copy text={"ERNÄHRUNG"}/></span><h1><Copy text={"Ernähre deinen Athleten."}/></h1><p><Copy text={"Der ERNÄHRUNG Wert bewertet deinen Tag nach Protein, Wasser, Obst und Gemüse, Zucker und verarbeiteten Lebensmitteln."}/></p></div><div className="hero-stat"><span><Copy text={"ERNÄHRUNG"}/></span><strong>{grade(today?.fuelScore)}</strong><small>{today?.fuelScore??"Keine Angabe"} / 100</small></div></section>
 <section className="progress-cards"><article className="panel"><span className="eyebrow"><Copy text={"HEUTE"}/></span><h2><Copy text={"Kalorienbilanz"}/></h2><div className="body-stats"><div><span><Copy text={"AUFNAHME"}/></span><strong>{today?.calories??"Keine Angabe"}</strong><small>kcal</small></div><div><span><Copy text={"VERBRAUCH"}/></span><strong>{expenditure??"Keine Angabe"}</strong><small><Copy text={wearable?"Gerätedaten plus Ausgangswert":"Daten fehlen"}/></small></div><div><span><Copy text={"BILANZ"}/></span><strong><Copy text={balance==null?"Keine Angabe":`${balance>0?"+":""}${balance}`}/></strong><small>kcal</small></div></div></article><article className="panel"><span className="eyebrow"><Copy text={"VERLAUF 7 TAGE"}/></span><h2><Copy text={"ERNÄHRUNG"}/></h2><div className="fake-chart fuel-chart">{items.slice(0,7).reverse().map(x=><i key={x.id} style={{height:`${Math.max(5,x.fuelScore??0)}%`}}/>)}</div></article></section><FuelClient/></main>}