import {useState} from "react";
import {Pressable,SafeAreaView,StyleSheet,Text,View} from "react-native";
import {CameraView,useCameraPermissions} from "expo-camera";
import {router} from "expo-router";
import {api} from "../lib/api";import {C,radius} from "../theme";
export default function Barcode(){
 const [permission,requestPermission]=useCameraPermissions();const [locked,setLocked]=useState(false);const [product,setProduct]=useState<any>(null);const [status,setStatus]=useState("");
 async function scan({data}:{data:string}){if(locked)return;setLocked(true);setStatus("LEBENSMITTEL WIRD GELADEN…");try{const x:any=await api("/api/food/barcode/"+encodeURIComponent(data));setProduct(x.product);setStatus("")}catch(e:any){setStatus(e.message||"Nicht gefunden.");setTimeout(()=>setLocked(false),1200)}}
 if(!permission)return <SafeAreaView style={s.safe}/>;
 if(!permission.granted)return <SafeAreaView style={s.safe}><View style={s.permission}><Text style={s.title}>CAMERA{"
"}PERMISSION.</Text><Text style={s.copy}>Die Kamera wird nur für den Barcode Scan verwendet.</Text><Pressable style={s.primary} onPress={requestPermission}><Text style={s.primaryText}>KAMERA ERLAUBEN →</Text></Pressable><Pressable onPress={()=>router.back()}><Text style={s.back}>BACK</Text></Pressable></View></SafeAreaView>;
 return <SafeAreaView style={s.safe}><View style={s.top}><Pressable onPress={()=>router.back()}><Text style={s.back}>← BACK</Text></Pressable><Text style={s.kicker}>BE FUEL BARCODE</Text></View><CameraView style={s.camera} facing="back" barcodeScannerSettings={{barcodeTypes:["ean13","ean8","upc_a","upc_e"]}} onBarcodeScanned={locked?undefined:scan}><View style={s.frame}/></CameraView>{product?<View style={s.sheet}><Text style={s.kicker}>FOUND</Text><Text style={s.product}>{product.name}</Text><Text style={s.copy}>{product.brand}</Text><View style={s.metrics}><Text style={s.metric}>{product.per100g.calories??"—"} kcal</Text><Text style={s.metric}>{product.per100g.proteinG??"—"} g Protein</Text><Text style={s.metric}>Nutri {product.officialNutriScore??"—"}</Text></View><Pressable style={s.primary} onPress={()=>router.replace({pathname:"/fuel",params:{calories:String(product.per100g.calories??""),proteinG:String(product.per100g.proteinG??""),carbsG:String(product.per100g.carbsG??""),fatG:String(product.per100g.fatG??"")}})}><Text style={s.primaryText}>WERTE ÜBERNEHMEN →</Text></Pressable><Pressable onPress={()=>{setProduct(null);setLocked(false)}}><Text style={s.rescan}>NOCHMAL SCANNEN</Text></Pressable></View>:<View style={s.hint}><Text style={s.copy}>{status||"Barcode in den Rahmen halten."}</Text></View>}</SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:C.bg},top:{height:58,paddingHorizontal:16,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},back:{color:C.ink,fontSize:9,fontWeight:"900",letterSpacing:1},kicker:{color:C.volt,fontSize:8,fontWeight:"900",letterSpacing:1.6},camera:{flex:1},frame:{width:"72%",aspectRatio:1.7,borderRadius:22,borderWidth:2,borderColor:C.volt,alignSelf:"center",marginTop:"48%",backgroundColor:"transparent"},hint:{padding:18,minHeight:72,alignItems:"center",justifyContent:"center"},sheet:{padding:20,backgroundColor:C.panel,borderTopWidth:1,borderTopColor:C.line},product:{color:C.ink,fontSize:25,fontWeight:"900",letterSpacing:-1,marginTop:6},copy:{color:C.dim,fontSize:12,lineHeight:18,marginTop:5},metrics:{flexDirection:"row",flexWrap:"wrap",gap:7,marginVertical:14},metric:{color:C.ink,fontSize:9,fontWeight:"900",borderWidth:1,borderColor:C.line,borderRadius:20,paddingVertical:7,paddingHorizontal:10},primary:{height:50,borderRadius:radius.md,backgroundColor:C.volt,alignItems:"center",justifyContent:"center",marginTop:6},primaryText:{color:C.bg,fontSize:9,fontWeight:"900",letterSpacing:1},rescan:{color:C.dim,fontSize:9,fontWeight:"900",textAlign:"center",paddingTop:16},permission:{flex:1,padding:24,justifyContent:"center"},title:{color:C.ink,fontSize:46,lineHeight:41,fontWeight:"900",letterSpacing:-3},});
