
import {Copy,ExerciseName,LocalizedTextInput} from "../components/Locale";


import {useEffect,useState} from "react";
import {ActivityIndicator,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,TextInput,View} from "react-native";
import {router} from "expo-router";
import Brand from "../components/Brand";import {Card,Eyebrow} from "../components/Card";import {api} from "../lib/api";import {C,radius} from "../theme";
export default function Library(){const [items,setItems]=useState<any[]|null>(null),[q,setQ]=useState("");async function load(query=""){setItems(null);try{const x:any=await api("/api/exercises"+(query?"?q="+encodeURIComponent(query):""));setItems(x.items)}catch{setItems([])}}useEffect(()=>{load()},[]);return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><View style={s.top}><Brand compact/><Pressable onPress={()=>router.back()}><Text style={s.back}><Copy text={"ZURÜCK"}/></Text></Pressable></View><Eyebrow><Copy text={"ÜBUNGSBIBLIOTHEK"}/></Eyebrow><Text style={s.title}><Copy text={"ANSEHEN."}/>{"\n"}<Copy text={"VERSTEHEN."}/>{"\n"}<Copy text={"SAUBER AUSFÜHREN."}/></Text><View style={s.search}><LocalizedTextInput style={s.input} value={q} onChangeText={setQ} placeholder="Übung oder Equipment" placeholderTextColor="#626864"/><Pressable style={s.searchBtn} onPress={()=>load(q)}><Text style={s.searchText}><Copy text={"SUCHEN"}/></Text></Pressable></View>{items===null?<ActivityIndicator color={C.volt}/>:items.map(x=><Pressable key={x.id} onPress={()=>router.push({pathname:"/exercise/[id]",params:{id:x.id}})}><Card><View style={s.row}><Text style={s.nr}>{x.id.slice(-3)}</Text><View style={s.flex}><Text style={s.name}><ExerciseName exercise={x}/></Text><Text style={s.meta}>{x.category.toUpperCase()}<Copy text={"· STUFE"}/>{x.level} · {x.equipment||"OHNE GERÄTE"}</Text></View><Text style={s.arrow}>→</Text></View></Card></Pressable>)}</ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:C.bg},content:{padding:18,paddingBottom:60,gap:10},top:{height:54,flexDirection:"row",justifyContent:"space-between",alignItems:"center"},back:{color:C.dim,fontSize:9,fontWeight:"900"},title:{color:C.ink,fontSize:46,lineHeight:40,fontWeight:"900",letterSpacing:-3,marginVertical:12},search:{flexDirection:"row",gap:7,marginBottom:4},input:{flex:1,height:50,borderRadius:radius.md,borderWidth:1,borderColor:C.line,backgroundColor:C.panel2,color:C.ink,paddingHorizontal:13},searchBtn:{width:52,borderRadius:radius.md,backgroundColor:C.volt,alignItems:"center",justifyContent:"center"},searchText:{color:C.bg,fontWeight:"900"},row:{flexDirection:"row",alignItems:"center",gap:11},nr:{color:"#343936",fontSize:26,fontWeight:"900"},flex:{flex:1},name:{color:C.ink,fontSize:16,fontWeight:"900"},meta:{color:C.dim,fontSize:8,fontWeight:"800",marginTop:4},arrow:{color:C.volt,fontSize:20}});
