
import {Copy} from "../components/Locale";
import {useRef,useState} from "react";
import {Pressable,SafeAreaView,StyleSheet,Text,View} from "react-native";
import {CameraView,useCameraPermissions} from "expo-camera";
import {router} from "expo-router";
import {api} from "../lib/api";import {C,radius} from "../theme";
export default function ProgressPhoto(){
 const camera=useRef<any>(null);const [permission,requestPermission]=useCameraPermissions();const [status,setStatus]=useState("");
 async function take(){if(!camera.current)return;setStatus("FOTO WIRD GESPEICHERT");try{const shot=await camera.current.takePictureAsync({quality:.9});await api("/api/consent",{method:"POST",body:JSON.stringify({type:"media_processing",version:"1.0",granted:true})});const form=new FormData();form.append("kind","PROGRESS_PHOTO");form.append("file",{uri:shot.uri,name:"fortschritt.jpg",type:"image/jpeg"} as any);await api("/api/media",{method:"POST",body:form});setStatus("FOTO PRIVAT GESPEICHERT");setTimeout(()=>router.back(),700)}catch(e:any){setStatus(e.message||"Foto konnte nicht gespeichert werden.")}}
 if(!permission)return <SafeAreaView style={s.safe}/>;
 if(!permission.granted)return <SafeAreaView style={s.safe}><View style={s.permission}><Text style={s.title}><Copy text={"DEIN"}/>{"\n"}<Copy text={"FORTSCHRITT."}/></Text><Text style={s.copy}><Copy text={"Das Bild bleibt privat und ist nur für dich und deinen Trainer sichtbar."}/></Text><Pressable style={s.primary} onPress={requestPermission}><Text style={s.primaryText}><Copy text={"KAMERA ERLAUBEN"}/></Text></Pressable><Pressable onPress={()=>router.back()}><Text style={s.back}><Copy text={"ZURÜCK"}/></Text></Pressable></View></SafeAreaView>;
 return <SafeAreaView style={s.safe}><View style={s.top}><Pressable onPress={()=>router.back()}><Text style={s.back}><Copy text={"← ZURÜCK"}/></Text></Pressable><Text style={s.kicker}><Copy text={"FORTSCHRITTSBILD"}/></Text></View><CameraView ref={camera} style={s.camera} facing="back"/><View style={s.controls}><Text style={s.copy}>{status||"Nutze möglichst gleiche Position und Beleuchtung."}</Text><Pressable style={s.primary} onPress={take}><Text style={s.primaryText}><Copy text={"FOTO AUFNEHMEN"}/></Text></Pressable></View></SafeAreaView>;
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:C.bg},top:{height:58,paddingHorizontal:16,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},back:{color:C.ink,fontFamily:"ManropeSemiBold",fontSize:11,},kicker:{color:C.volt,fontFamily:"ManropeSemiBold",fontSize:11,letterSpacing:1.4},camera:{flex:1},controls:{padding:18},copy:{color:C.dim,fontFamily:"Manrope",fontSize:12,lineHeight:18,textAlign:"center"},primary:{height:52,borderRadius:radius.md,backgroundColor:C.volt,alignItems:"center",justifyContent:"center",marginTop:12},primaryText:{color:C.bg,fontFamily:"ManropeSemiBold",fontSize:11,},permission:{flex:1,padding:24,justifyContent:"center"},title:{color:C.ink,fontFamily:"Archivo",fontSize:36,lineHeight:40,letterSpacing:-.8}});
