
import {Copy} from "../components/Locale";
import {useRef,useState} from "react";
import {Pressable,SafeAreaView,StyleSheet,Text,View} from "react-native";
import {CameraView,useCameraPermissions,useMicrophonePermissions} from "expo-camera";
import {router} from "expo-router";
import {api} from "../lib/api";import {C,radius} from "../theme";
export default function TechniqueVideo(){
 const camera=useRef<any>(null);const [cam,askCam]=useCameraPermissions();const [mic,askMic]=useMicrophonePermissions();const [recording,setRecording]=useState(false),[status,setStatus]=useState("");
 async function start(){if(!camera.current||recording)return;setRecording(true);setStatus("AUFNAHME LÄUFT");try{const result=await camera.current.recordAsync({maxDuration:60});if(result?.uri)await upload(result.uri)}catch(e:any){setStatus(e.message||"Aufnahme fehlgeschlagen.")}finally{setRecording(false)}}
 function stop(){camera.current?.stopRecording()}
 async function upload(uri:string){setStatus("VIDEO WIRD HOCHGELADEN");await api("/api/consent",{method:"POST",body:JSON.stringify({type:"media_processing",version:"1.0",granted:true})});const form=new FormData();form.append("kind","TECHNIQUE_VIDEO");form.append("file",{uri,name:"technikvideo.mp4",type:"video/mp4"} as any);const up:any=await api("/api/media",{method:"POST",body:form});await api("/api/messages",{method:"POST",body:JSON.stringify({kind:"VIDEO",mediaId:up.asset.id,text:"Technikvideo zur Analyse"})});setStatus("VIDEO AN DEN TRAINER GESENDET");setTimeout(()=>router.back(),900)}
 if(!cam||!mic)return <SafeAreaView style={s.safe}/>;
 if(!cam.granted||!mic.granted)return <SafeAreaView style={s.safe}><View style={s.permission}><Text style={s.title}><Copy text={"KAMERA UND"}/>{"\n"}<Copy text={"MIKROFON."}/></Text><Text style={s.copy}><Copy text={"Für dein Technikvideo werden Kamera und Mikrofon nur während der Aufnahme verwendet."}/></Text><Pressable style={s.primary} onPress={async()=>{await askCam();await askMic()}}><Text style={s.primaryText}><Copy text={"BERECHTIGUNG ERLAUBEN"}/></Text></Pressable><Pressable onPress={()=>router.back()}><Text style={s.back}><Copy text={"ZURÜCK"}/></Text></Pressable></View></SafeAreaView>;
 return <SafeAreaView style={s.safe}><View style={s.top}><Pressable onPress={()=>router.back()}><Text style={s.back}><Copy text={"← ZURÜCK"}/></Text></Pressable><Text style={s.kicker}><Copy text={"TECHNIKVIDEO"}/></Text></View><CameraView ref={camera} style={s.camera} facing="back" mode="video"/><View style={s.controls}><Text style={s.copy}>{status||"Maximal 60 Sekunden. Zeige die Bewegung vollständig."}</Text><Pressable style={[s.record,recording&&s.stop]} onPress={recording?stop:start}><Text style={s.recordText}><Copy text={recording?"AUFNAHME BEENDEN":"AUFNAHME STARTEN"}/></Text></Pressable></View></SafeAreaView>;
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:C.bg},top:{height:58,paddingHorizontal:16,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},back:{color:C.ink,fontFamily:"ManropeSemiBold",fontSize:11,},kicker:{color:C.volt,fontFamily:"ManropeSemiBold",fontSize:11,letterSpacing:1.4},camera:{flex:1},controls:{padding:18},copy:{color:C.dim,fontFamily:"Manrope",fontSize:12,lineHeight:18,textAlign:"center"},record:{height:54,borderRadius:radius.md,backgroundColor:C.volt,alignItems:"center",justifyContent:"center",marginTop:12},stop:{backgroundColor:C.red},recordText:{color:C.bg,fontFamily:"ManropeSemiBold",fontSize:11,},permission:{flex:1,padding:24,justifyContent:"center"},title:{color:C.ink,fontFamily:"Archivo",fontSize:36,lineHeight:40,letterSpacing:-.8},primary:{height:52,borderRadius:radius.md,backgroundColor:C.volt,alignItems:"center",justifyContent:"center",marginTop:18},primaryText:{color:C.bg,fontFamily:"ManropeSemiBold",fontSize:11,}});
