
import {Copy} from "../components/Locale";


import {useCallback,useEffect,useState} from "react";
import {Linking,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,View} from "react-native";
import {router,useFocusEffect} from "expo-router";
import Brand from "../components/Brand";
import {Card,Eyebrow,SectionTitle} from "../components/Card";
import {api} from "../lib/api";
import {syncHealth} from "../lib/health";
import {C,radius} from "../theme";
const names:Record<string,string>={garmin:"Garmin",polar:"Polar",suunto:"Suunto",coros:"COROS",whoop:"WHOOP",oura:"Oura",fitbit:"Fitbit"};
const phoneBrands=[
 ["APPLE WATCH","Apple Health"],["SAMSUNG GALAXY WATCH","Android Health Connect"],["XIAOMI / MI FITNESS","Android Health Connect"],["GOOGLE PIXEL WATCH","Android Health Connect"]
] as const;
export default function Wearables(){
 const [d,setD]=useState<any>({items:[],providers:[]}),[status,setStatus]=useState(""),[busy,setBusy]=useState(false);
 async function load(){const x:any=await api("/api/wearables/connections");setD(x)}
 useFocusEffect(useCallback(()=>{load().catch(e=>setStatus(e.message))},[]));
 async function device(){if(busy)return;setBusy(true);setStatus("SYNCHRONISIERE");try{await syncHealth();setStatus("GESUNDHEITSDATEN AKTUALISIERT")}catch(e:any){setStatus(e.message||"Synchronisierung fehlgeschlagen")}finally{setBusy(false)}}
 async function connect(x:any,action="connect"){if(busy)return;setBusy(true);try{const r:any=await api("/api/wearables/connections",{method:"POST",body:JSON.stringify({provider:x.provider,action})});if(r.connectUrl){await Linking.openURL(r.connectUrl)}else{setStatus(r.pending?"Synchronisierung angefordert.":r.revokePending?"Lokal getrennt. Bitte erneut trennen.":action==="disconnect"?"VERBINDUNG GETRENNT":"DATEN SYNCHRONISIERT");await load()}}catch(e:any){setStatus(e.message||"Verbindung fehlgeschlagen.")}finally{setBusy(false)}}

 const connected=new Map((d.items||[]).map((x:any)=>[x.provider,x]));
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><View style={s.top}><Brand compact/><Pressable onPress={()=>router.back()}><Text style={s.back}><Copy text={"ZURÜCK"}/></Text></Pressable></View><Eyebrow><Copy text={"GESUNDHEITSDATEN"}/></Eyebrow><Text style={s.title}><Copy text={"EINE SICHT"}/>{"\n"}<Copy text={"AUF DEINE DATEN."}/></Text><Card><Eyebrow>GADGETS</Eyebrow><SectionTitle>Apple, Samsung, Xiaomi und mehr</SectionTitle><Text style={s.copy}>Die App liest nur Daten, die du über Apple Health oder Android Health Connect freigibst. Bei Samsung und Xiaomi hängt die Verfügbarkeit davon ab, welche Daten die Hersteller App an Health Connect weitergibt.</Text><View style={s.brandGrid}>{phoneBrands.map(([brand,via])=><View style={s.brandChip} key={brand}><Text style={s.brandName}>{brand}</Text><Text style={s.brandVia}>{via}</Text></View>)}</View><Pressable style={s.primary} disabled={busy} onPress={device}><Text style={s.primaryText}><Copy text={"JETZT SYNCHRONISIEREN"}/></Text></Pressable></Card><Card><Eyebrow><Copy text={"WEITERE ANBIETER"}/></Eyebrow><SectionTitle><Copy text={"Eine Verbindung pro Anbieter"}/></SectionTitle>{(d.providers||[]).map((x:any)=>{const item:any=connected.get(x.provider);return <View style={s.row} key={x.provider}><View style={{flex:1}}><Text style={s.name}>{names[x.provider]||x.provider}</Text><Text style={s.note}><Copy text={item?.status==="CONNECTED"?"VERBUNDEN":x.configured?"BEREIT":"NOCH NICHT AKTIVIERT"}/></Text></View><Pressable style={s.small} disabled={busy||!x.configured} onPress={()=>connect(x,item?.status==="CONNECTED"?"sync":"connect")}><Text style={s.smallText}><Copy text={item?.status==="CONNECTED"?"SYNC":"VERBINDEN"}/></Text></Pressable>{item&&<Pressable style={s.small} disabled={busy} onPress={()=>connect(x,"disconnect")}><Text style={s.smallText}><Copy text={"TRENNEN"}/></Text></Pressable>}</View>})}</Card><Card><Eyebrow><Copy text={"DATENLOGIK"}/></Eyebrow><Text style={s.copy}><Copy text={"Werte verschiedener Hersteller werden gegen deinen persönlichen Verlauf bewertet. Fehlende Daten bleiben als unvollständig sichtbar und werden nicht erfunden."}/></Text></Card>{status?<Text style={s.status}><Copy text={status}/></Text>:null}</ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:C.bg},content:{padding:18,paddingBottom:70,gap:12},top:{height:54,flexDirection:"row",justifyContent:"space-between",alignItems:"center"},back:{color:C.dim,fontFamily:"ManropeSemiBold",fontSize:11,},title:{color:C.ink,fontFamily:"Archivo",fontSize:36,lineHeight:40,letterSpacing:-.8,marginVertical:12},copy:{color:C.dim,fontFamily:"Manrope",fontSize:11,lineHeight:18,marginTop:10},primary:{height:50,borderRadius:radius.md,backgroundColor:C.volt,alignItems:"center",justifyContent:"center",marginTop:14},primaryText:{color:C.bg,fontFamily:"ManropeSemiBold",fontSize:11,},row:{minHeight:62,flexDirection:"row",alignItems:"center",gap:10,borderBottomWidth:1,borderBottomColor:C.line},name:{color:C.ink,fontFamily:"ManropeSemiBold",fontSize:12,},note:{color:C.dim,fontFamily:"Manrope",fontSize:11,marginTop:3},small:{minWidth:86,height:38,borderRadius:12,borderWidth:1,borderColor:C.line,alignItems:"center",justifyContent:"center"},smallText:{color:C.volt,fontFamily:"ManropeSemiBold",fontSize:11,},brandGrid:{flexDirection:"row",flexWrap:"wrap",gap:7,marginTop:14},brandChip:{width:"48.5%",padding:10,backgroundColor:"#101416",borderTopWidth:1,borderTopColor:C.line},brandName:{color:C.ink,fontFamily:"ManropeSemiBold",fontSize:10},brandVia:{color:C.dim,fontFamily:"Manrope",fontSize:9,marginTop:3},status:{color:C.green,fontFamily:"Manrope",fontSize:11,textAlign:"center"}});
