"use client";
import {Copy,LocalizedElement} from "../../components/Locale";

import {useEffect,useState} from "react";
import Link from "next/link";
export default function AIReview(){
 const [data,setData]=useState<any>({items:[],handoffs:[]}),[notes,setNotes]=useState<Record<string,string>>({}),[status,setStatus]=useState(''),[busy,setBusy]=useState(false);
 async function load(){const r=await fetch('/api/admin/ai');if(!r.ok)throw Error('Daten konnten nicht geladen werden.');setData(await r.json())}
 useEffect(()=>{load().catch(e=>setStatus(e.message))},[]);
 async function action(body:any){setBusy(true);try{const r=await fetch('/api/admin/ai',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw Error(d.error);setStatus('Gespeichert.');await load()}catch(e:any){setStatus(e.message)}finally{setBusy(false)}}
 return <main className="admin-content" style={{margin:'0 auto'}}><header className="admin-header"><h1><Copy text={"Trainer Kontrolle"}/></h1><Link href="/admin"><Copy text={"← ÜBERSICHT"}/></Link></header><article className="panel"><h2><Copy text={"Übergaben"}/></h2>{data.handoffs.map((h:any)=><details key={h.id}><summary>{h.user?.name||h.user?.email} · {h.status}</summary><p>{h.summary}</p><p>{h.reason}</p>{h.status!=='RESOLVED'?<><label><Copy text={"Antwort des Trainers"}/><textarea value={notes[h.id]||''} onChange={e=>setNotes({...notes,[h.id]:e.target.value})}/></label><div className="row-actions"><button disabled={busy} className="secondary" onClick={()=>action({action:'claim',handoffId:h.id})}><Copy text={"ÜBERNEHMEN"}/></button><button disabled={busy||!notes[h.id]?.trim()} className="primary" onClick={()=>action({action:'resolve',handoffId:h.id,reply:notes[h.id]})}><Copy text={"ANTWORTEN UND ABSCHLIESSEN"}/></button></div></>:<p>{h.resolution}</p>}</details>)}</article><article className="panel"><h2><Copy text={"AI Antworten prüfen"}/></h2>{data.items.map((m:any)=><details key={m.id}><summary>{m.user?.name||m.user?.email} · <Copy text={m.coachReviewedAt?'GEPRÜFT':'OFFEN'}/></summary><p>{m.content}</p>{!m.coachReviewedAt&&<><LocalizedElement as="textarea" aria-label="Ergänzung des Trainers" value={notes[m.id]||''} onChange={e=>setNotes({...notes,[m.id]:e.target.value})}/><button disabled={busy} onClick={()=>action({action:'review',messageId:m.id,replacement:notes[m.id]?.trim()||undefined})}><Copy text={"PRÜFEN"}/></button></>}</details>)}</article>{data.canConfigure&&data.settings&&<form className="panel" onSubmit={e=>{e.preventDefault();action({action:'settings',settings:data.settings})}}><h2><Copy text={"AI Einstellungen"}/></h2><label><input type="checkbox" checked={data.settings.enabled} onChange={e=>setData({...data,settings:{...data.settings,enabled:e.target.checked}})}/><Copy text={"AI AKTIV"}/></label><label><input type="checkbox" checked={data.settings.afterHoursOnly} onChange={e=>setData({...data,settings:{...data.settings,afterHoursOnly:e.target.checked}})}/><Copy text={"NUR AUSSERHALB DER TRAINERZEIT"}/></label>{(['coachFrom','coachTo','dailyLimit'] as const).map(k=><label key={k}>{k}<input type="number" required value={data.settings[k]} onChange={e=>setData({...data,settings:{...data.settings,[k]:Number(e.target.value)}})}/></label>)}<label><Copy text={"Zeitzone"}/><input required value={data.settings.timezone} onChange={e=>setData({...data,settings:{...data.settings,timezone:e.target.value}})}/></label><label><Copy text={"Ton des Trainers"}/><textarea maxLength={600} value={data.settings.tone} onChange={e=>setData({...data,settings:{...data.settings,tone:e.target.value}})}/></label><button disabled={busy} className="primary"><Copy text={"SPEICHERN"}/></button></form>}<p role="status"><Copy text={status}/></p></main>
}
