
import {Copy} from "../../components/Locale";
import {useCallback,useState} from "react";
import {Pressable,StyleSheet,Text,View} from "react-native";
import {router,useFocusEffect} from "expo-router";
import Screen from "../../components/Screen";
import {Card,Eyebrow,SectionTitle} from "../../components/Card";
import {api} from "../../lib/api";
import {C,radius} from "../../theme";

export default function Progress(){
 const [d,setD]=useState<any>({});
 useFocusEffect(useCallback(()=>{Promise.all([api<any>("/api/mobile/dashboard"),api<any>("/api/body-metrics"),api<any>("/api/performance-tests")]).then(([dash,body,tests])=>setD({dash,body:body.items,tests:tests.items})).catch(()=>{})},[]));
 const score=d.dash?.score,body=d.body?.[0],locked=d.dash?.scoreDetailsLocked;
 return <Screen>
  <View style={s.hero}><Eyebrow><Copy text={"FORTSCHRITT"}/></Eyebrow><Text style={s.big}><Copy text={"ZEIG ES"}/>{String.fromCharCode(10)}<Copy text={"MIT DATEN."}/></Text></View>
  <View style={s.grid}><Card style={s.metric}><Eyebrow><Copy text={"LEISTUNGSWERT"}/></Eyebrow><Text style={s.number}>{score?.total??"Keine Angabe"}</Text><Text style={s.unit}><Copy text={"AKTUELL"}/></Text></Card><Card style={s.metric}><Eyebrow><Copy text={"GEWICHT"}/></Eyebrow><Text style={s.number}>{body?.weightKg??"Keine Angabe"}</Text><Text style={s.unit}>KG</Text></Card></View>
  {locked?<Card><Eyebrow>PRO</Eyebrow><SectionTitle><Copy text={"Dein vollständiges Leistungsprofil"}/></SectionTitle><Text style={s.copy}><Copy text={"KOSTENLOS zeigt den Gesamtwert. PRO zeigt alle Leistungsbereiche, deren Verlauf und die Erklärungen dahinter."}/></Text><Pressable style={s.primary} onPress={()=>router.push("/membership")}><Text style={s.primaryText}><Copy text={"PRO FREISCHALTEN"}/></Text></Pressable></Card>:<Card><Eyebrow><Copy text={"LEISTUNGSBEREICHE"}/></Eyebrow><SectionTitle><Copy text={"Leistungsprofil"}/></SectionTitle>{[["Kraft",score?.strength],["Ausdauer",score?.endurance],["Athletik",score?.athleticism],["Beweglichkeit",score?.mobility],["Regeneration",score?.recovery],["Ernährung",score?.fuel],["Beständigkeit",score?.consistency]].map(([n,v]:any)=><View style={s.pillar} key={n}><Text style={s.pillarName}>{String(n).toUpperCase()}</Text><View style={s.track}><View style={[s.fill,{width:`${v??0}%`}]}/></View><Text style={s.val}>{v??"Keine Angabe"}</Text></View>)}</Card>}
  <Card><Eyebrow>BE DIFFERENT TEST</Eyebrow><SectionTitle><Copy text={"Verlauf"}/></SectionTitle>{d.tests?.length?d.tests.slice(0,6).map((t:any)=><View style={s.test} key={t.id}><View><Text style={s.pillarName}>{t.name}</Text><Text style={s.unit}>{t.completedAt?new Date(t.completedAt).toLocaleDateString("de-DE"):"GEPLANT"}</Text></View><Text style={s.testVal}>{t.results?.[0]?.value??"Keine Angabe"} {t.results?.[0]?.unit??""}</Text></View>):<Text style={s.empty}><Copy text={"Noch kein Test gespeichert."}/></Text>}<Pressable style={s.link} onPress={()=>router.push("/tests")}><Text style={s.linkText}><Copy text={"ALLE TESTS →"}/></Text></Pressable></Card>
  <Card><Eyebrow><Copy text={"DEINE ENTWICKLUNG"}/></Eyebrow><Pressable style={s.row} onPress={()=>router.push("/progress-photos")}><Text style={s.rowText}><Copy text={"VORHER NACHHER VERGLEICH"}/></Text><Text style={s.arrow}>→</Text></Pressable><Pressable style={s.row} onPress={()=>router.push("/digital-twin")}><Text style={s.rowText}><Copy text={"DIGITALER ATHLET"}/></Text><Text style={s.arrow}>→</Text></Pressable><Pressable style={s.row} onPress={()=>router.push("/performance-timeline")}><Text style={s.rowText}><Copy text={"LEISTUNGSVERLAUF"}/></Text><Text style={s.arrow}>→</Text></Pressable><Pressable style={s.row} onPress={()=>router.push("/report")}><Text style={s.rowText}><Copy text={"WOCHENBERICHT"}/></Text><Text style={s.arrow}>→</Text></Pressable></Card>
 </Screen>
}
const s=StyleSheet.create({hero:{paddingVertical:18},big:{color:C.ink,fontSize:49,lineHeight:42,fontWeight:"900",letterSpacing:-3,marginTop:10},grid:{flexDirection:"row",gap:10},metric:{flex:1},number:{color:C.ink,fontSize:44,fontWeight:"900",letterSpacing:-3,marginTop:10},unit:{color:C.dim,fontSize:8,fontWeight:"800",letterSpacing:1},pillar:{flexDirection:"row",alignItems:"center",gap:9,paddingVertical:10},pillarName:{width:96,color:C.dim,fontSize:8,fontWeight:"900",letterSpacing:.8},track:{flex:1,height:4,backgroundColor:"#282C2A"},fill:{height:"100%",backgroundColor:C.volt},val:{width:48,textAlign:"right",color:C.ink,fontSize:11,fontWeight:"800"},test:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",paddingVertical:13,borderBottomWidth:1,borderBottomColor:C.line},testVal:{color:C.ink,fontWeight:"900"},empty:{color:C.dim,fontSize:12,marginTop:16},copy:{color:C.dim,fontSize:11,lineHeight:18,marginTop:10},primary:{height:48,borderRadius:radius.md,backgroundColor:C.volt,alignItems:"center",justifyContent:"center",marginTop:14},primaryText:{color:C.bg,fontSize:9,fontWeight:"900"},link:{height:44,alignItems:"center",justifyContent:"center",marginTop:8},linkText:{color:C.volt,fontSize:8,fontWeight:"900"},row:{height:52,flexDirection:"row",alignItems:"center",borderBottomWidth:1,borderBottomColor:C.line},rowText:{flex:1,color:C.ink,fontSize:10,fontWeight:"900"},arrow:{color:C.volt,fontSize:17}});
